spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/tulpar
    username:
    password:

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: redis_secret
      ssl:
        enabled: false

management:
  endpoint:
    health:
      show-details: always

firebase:
  service-account-path: firebase-service-account.json
  project-id: tulpar-19a6c

minio:
  endpoint: ${R2_ENDPOINT:https://c5ba9bd76f3a4f23ced42727fd962f34.r2.cloudflarestorage.com}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET:tulpar}
  public-url: ${R2_PUBLIC_URL:https://pub-cfcd1f8d9d334d638e5c522acf05a60b.r2.dev}
  presigned-url-expiry: 3600

ai:
  openai:
    api-key: ${PERPLEXITY_API_KEY}
    base-url: https://api.perplexity.ai
    model: sonar

logging:
  level:
    root: INFO
    kz.diploma.tulpar: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
