package kz.diploma.tulpar.domain.enums;

public enum ExerciseType {
    VOCABULARY,          // choose translation / word matching
    SENTENCE_BUILDER,    // arrange shuffled words into a sentence
    LISTENING,           // audio playback + multiple choice
    VIDEO_CONTEXT,       // short movie clip + missing phrase
    IMAGE_CONTEXT,       // image + describe or choose phrase
    AI_GENERATED         // dynamically generated by AI
}
